ai_tech = ['Data management and query software',
'Business function specific software',
'Industry specific software',
'Calculating machines and accessories',
'Sorting machines',
'Phone and video conference equipment and hardware and controllers',
'Robotics',
'Programmable Logic Controllers',
'Actuators',
'Surface data logging equipment',
'Integrated circuits',
'Clinical and diagnostic analyzers and accessories and supplies',
'Diagnostic assessment and exam products for general use',
'Electrocardiography EKG units and related products',
'Pulse oximeters',
'Neurological exam products',
'Medical documentation products',
'Medical computed tomography CT or CAT systems and related products',
'Medical magnetic resonance imaging MRI products',
'Medical ultrasound and doppler and echo imaging products',
'Medical diagnostic x ray products',
'Medical diagnostic gamma cameras and related products',
'Medical imaging processing equipment and supplies',
'Communication aids for the physically challenged',
'Intravenous and arterial catheter and needle positioning aids',
'Intravenous or arterial flow measurement and regulation products',
'Intravenous infusion pumps and its analyzers and sensors and its accessories',
'Needleless intravenous injection and withdrawal systems',
'Blood administration and transfusion products',
'Breast feeding equipment and supplies',
'Cognitive and dexterity and perceptual and sensory evaluation and therapy products',
'Oxygen therapy delivery systems and devices',
'Pulmonary function testing and treatment products',
'Personal communication devices',
'Media storage devices',
'Data management and query software',
'Development software',
'Educational or reference software',
'Industry specific software',
'Network applications software',
'Network management software',
'Networking software',
'Operating environment software',
'Security and protection software',
'Utility and device driver software',
'Information exchange software',
'System management software',
'Finance accounting and enterprise resource planning ERP software',
'Computer game or entertainment software',
'Content authoring and editing software',
'Content management software',
'Traffic control',
'Surveillance and detection equipment',
'Piece and part vending machines',
'Service and ticket vending machines',
'Domestic kitchen appliances',
'Domestic laundry appliances and supplies',
'Domestic bath appliances',
'Other domestic household appliances',
'Electronic publications and music',
'Food preparation machinery',
'Agricultural machinery for soil preparation',
'Agricultural machinery for planting and seeding',
'Agricultural machinery for harvesting',
'Dispersing and spraying appliances for agriculture',
'Poultry and livestock equipment',
'Agricultural machinery for cleaning and sorting and grading',
'Industrial trucks',
'Product and material transport vehicles',
'Steering system',
'Specialized vehicle systems and components',
'Electric vehicle charging systems',
'Aerospace location and navigation systems and components',
'Power generation monitoring or detecting equipment',
'Precision hand tools',
'Circuit assemblies and radio frequency RF components',
'Diodes',
'Resistors',
'Discrete components',
'Special effects devices',
'Electrical controls and accessories',
'Circuit protection devices and accessories',
'Electrical hardware and supplies',
'Electrical switches and accessories',
'Electrical relays and accessories',
'Nucleic acid extraction and purification and quantitation kits and components',
'Deoxyribonucleic acid DNA analysis kits',
'Polymerase chain reaction PCR and reverse transcriptase polymerase chain reaction RT PCR products',
'Weight measuring instruments',
'Microorganism propagation and transformation media and kits and equipment',
'Electrical measuring and testing equipment and accessories']
