automating_tech = ['Igniters',
 'Emulsion breakers',
 'Fission fuel assemblies',
 'Cutting equipment',
 'Screens and feeding equipment',
 'Crushers and breakers and grinders',
 'Mechanized ground support systems',
 'Secondary rock breaking systems',
 'Exploration and development systems',
 'Rock drills',
 'Explosive loading machinery',
 'Underground mining service vehicles',
 'Drilling and operation machinery',
 'Drilling and operation accessories',
 'Cementing equipment',
 'Sand control equipment',
 'Completion tools and equipment',
 'Conventional drilling tools',
 'Well measurement and logging equipment',
 'Perforating equipment',
 'Well testing equipment',
 'Slickline equipment',
 'Production systems equipment',
 'Coiled tubing equipment',
 'Seismic equipment',
 'Oil country tubular goods',
 'Drilling and workover rigs and equipment',
 'Surface data logging equipment',
 'Wellhead equipment',
 'Downhole jet pumps and anchors',
 'Downhole pumps',
 'Heater treaters',
 'Produced water treating equipment',
 'Pumping units',
 'Production separators',
 'Agricultural machinery for soil preparation',
 'Agricultural machinery for planting and seeding',
 'Agricultural machinery for harvesting',
 'Dispersing and spraying appliances for agriculture',
 'Poultry and livestock equipment',
 'Agricultural machinery for cleaning and sorting and grading',
 'Forestry machinery and equipment',
 'Greenhouse equipment',
 'Commercial fishing equipment',
 'Aquaculture equipment',
 'Earth moving machinery',
 'Paving equipment',
 'Heavy equipment components',
 'Aerial lifts',
 'Building construction machinery and accessories',
 'Building demolition machinery and equipment',
 'Machinery for working wood and stone and ceramic and the like',
 'Petroleum distilling and processing machinery and equipment',
 'Textile processing machinery and accessories',
 'Textile working machinery and equipment and accessories',
 'Grinding and sanding and polishing equipment and supplies',
 'Faceting equipment and accessories',
 'Leather preparing machinery and accessories',
 'Leather working and repairing machinery and accessories',
 'Rubber and plastic processing machinery and equipment and supplies',
 'Cement and ceramics and glass industry machinery and equipment and supplies',
 'Optical industry machinery and equipment and supplies',
 'Pharmaceutical industry machinery and equipment and supplies',
 'Paper making and paper processing machinery and equipment and supplies',
 'Web handling and control machinery and equipment and supplies',
 'Separation machinery and equipment',
 'Manufacturing tables and stands',
 'Packaging machinery',
 'Holding and positioning and guiding systems and devices',
 'Industrial machinery components and accessories',
 'Robotics',
 'Assembly machines',
 'Paint systems',
 'Part marking machines',
 'Coating systems',
 'Foundry machines and equipment',
 'Foundry supplies',
 'Food preparation machinery',
 'Food cutting machinery',
 'Food cooking and smoking machinery',
 'Industrial beverage processing machinery',
 'Batch mixers',
 'Continuous mixers',
 'Gas liquid contacting systems',
 'Industrial drying equipment',
 'Electronic manufacturing and processing machinery',
 'Killing and defeathering department machinery and equipment',
 'Bandsaws and accessories',
 'Metal grinding machines',
 'Metal cutting machines',
 'Metal cutting tools',
 'Metal deburring machines',
 'Metal drilling machines',
 'Metal boring machines',
 'Metal cutting machine attachments',
 'Lathes and turning centers',
 'Machining centers',
 'Metal milling machines',
 'Specialized or miscellaneous metal cutting machines',
 'Metal bending machines',
 'Metal rolling machines',
 'Forging machines',
 'Metal forming dies and tooling',
 'Rapid prototyping machines',
 'Welding machinery',
 'Soldering machines',
 'Welding and soldering and brazing accessories',
 'Welding and soldering and brazing supplies',
 'Coating or plating machines',
 'Heat treating machines',
 'Mechanical surface treatment machines',
 'Metal cleaning machinery and supplies',
 'Industrial reaming tools',
 'Industrial threading tools',
 'Industrial trucks',
 'Lifting equipment and accessories',
 'Conveyors and accessories',
 'Drum handling equipment',
 'Packing tools',
 'Locomotives and electric trolleys',
 'Steering system',
 'Specialized vehicle systems and components',
 'Product and material trailers',
 'Aerospace location and navigation systems and components',
 'Flight communications related systems',
 'Aircraft master control systems',
 'Aircraft emergency systems',
 'Aircraft power systems',
 'Flight instrumentation',
 'Aircraft landing and braking systems',
 'Aircraft fuel tanks and systems',
 'Aircraft equipment',
 'Aircraft accumulators',
 'Electric alternating current AC motors',
 'Electric direct current DC motors',
 'Non electric motors',
 'Engines',
 'Engine components and accessories',
 'Kinetic power transmission',
 'Power generators',
 'Batteries and cells and accessories',
  'Power plants',
 'Power generation monitoring or detecting equipment',
 'Power generation control equipment',
 'Cutting and crimping and punching tools',
 'Forming tools',
 'Power tools',
 'Tool kits',
 'Hydraulic presses',
 'Hydraulic cylinders and pistons',
 'Hydraulic hose and tube fittings',
 'Hydraulic tools',
 'Pneumatic tools',
 'Actuators',
 'Circuit assemblies and radio frequency RF components',
 'Integrated circuits',
 'Diodes',
 'Resistors',
 'Programmable Logic Controllers',
 'Special effects devices',
 'Electrical controls and accessories',
 'Circuit protection devices and accessories',
 'Electrical hardware and supplies',
 'Electrical switches and accessories',
 'Electrical relays and accessories',
 'Wire Markers and Wire Marking Devices',
 'Hardware and fittings',
 'Fluid and gas regulators',
 'Traps and strainers',
 'Pumps',
 'Compressors',
 'Filters',
 'Purification',
 'Separators',
 'Filter media',
 'Pipe spectacle blind flanges',
 'Laboratory blending and dispersing and homogenizing equipment and supplies',
 'Laboratory boring and grinding and cutting and crushing and pressing equipment',
 'Laboratory electron and solid state physics equipment',
 'Laboratory ionic equipment',
 'Laboratory heating and drying equipment',
 'Laboratory entomological equipment and accessories',
 'Animal laboratory equipment and accessories',
 'Crystallography equipment',
 'Histology equipment',
 'Laboratory cooling equipment',
 'Laboratory washing and cleaning equipment',
 'Fluid mechanics equipment',
 'Laboratory environmental conditioning equipment',
 'Laboratory enclosures and accessories',
 'Laboratory baths',
 'Laboratory mixing and stirring and shaking equipment and supplies',
 'Laboratory centrifuges and accessories',
 'Sampling equipment',
 'Specimen collection and transport containers and supplies',
 'Laboratory water purification equipment and supplies',
 'Fermentation equipment',
 'Laboratory incubating equipment',
 'Laboratory ovens and accessories',
 'Laboratory furnaces and accessories',
 'Laboratory freeze dryers and lyopholizers and accessories',
 'Laboratory decanting and distilling and evaporating and extracting equipment and supplies',
 'Laboratory filtering equipment and supplies',
 'Laboratory sieves and sifting equipment and supplies',
 'Laboratory pumps and tubing',
 'Laboratory slide stainer equipment and accessories',
 'Laboratory electrophoresis and blotting system and supplies',
 'Nucleic acid extraction and purification and quantitation kits and components',
 'Libraries and related materials',
 'Deoxyribonucleic acid DNA analysis kits',
 'Microorganism propagation and transformation media and kits and equipment',
 'Polymerase chain reaction PCR and reverse transcriptase polymerase chain reaction RT PCR products',
 'Vectors',
 'Weight measuring instruments',
 'Length and thickness and distance measuring instruments',
 'Transducers',
 'Pressure measuring and control instruments',
 'Liquid and gas flow measuring and observing instruments',
 'Seed and feed equipment',
 'Transportation related equipment and instruments',
 'Navigational equipment and instruments',
 'Chemical evaluation instruments and supplies',
 'Gas analyzers and monitors',
 'Liquid and solid and elemental analyzers',
 'Nuclear evaluation instruments',
 'Electrical measuring and testing equipment and accessories',
 'Electronic and communication measuring and testing instruments',
 'Geophysical and geotechnical instruments',
 'Soil measuring equipment',
 'Rock and strata measuring equipment',
 'Seismological instruments',
 'Land surveying instruments',
 'Hydrological instruments',
 'Meteorological instruments',
 'Mechanical instruments',
 'Metals and metallurgy and structural materials testing instruments',
 'Paper and wood and textile testing instruments',
 'Radar and sonar systems and components',
 'Light and wave generating and measuring equipment',
 'Spectroscopic equipment',
 'Sound generating and measuring equipment',
 'Electrochemical measuring instruments and accessories',
 'Chromatographic measuring instruments and accessories',
 'Clinical and diagnostic analyzers and accessories and supplies',
 'Acceleration and vibration measuring instruments',
 'General laboratory storage containers and cabinets',
 'Dosing devices',
 'Veterinary artificial insemination equipment and supplies',
 'Decubitus prevention products',
 'Enema administration supplies',
 'Medical documentation products',
 'Dental and subspecialty instruments and devices',
 'Dental imaging equipment and supplies',
 'Dental laboratory and sterilization equipment and supplies',
 'Dental lasers and illumination and fiber optic equipment and supplies',
 'Peritoneal and equilibrium dialysis equipment and supplies',
 'Extracorporeal hemodialysis equipment and supplies',
 'Continuous renal replacement therapy CRRT equipment and supplies',
 'Emergency medical services disaster management products',
 'Emergency medical services extricating and immobilizing and transporting products',
 'Emergency medical services airway management equipment',
 'Emergency and field medical services kits',
 'Emergency medical services resuscitation products',
 'Emergency medical services supplies',
 'Diagnostic assessment and exam products for general use',
 'Blood pressure units and related products',
 'Electrocardiography EKG units and related products',
 'Pulse oximeters',
 'Acute care monitoring units and related products',
 'Neurological exam products',
 'Hearing testing products',
 'Ophthalmic diagnostic exam products',
 'Medical equipment transport and transfer products',
 'Medication dispensing and measuring devices and supplies',
 'Medical computed tomography CT or CAT systems and related products',
 'Medical magnetic resonance imaging MRI products',
 'Medical ultrasound and doppler and echo imaging products',
 'Medical diagnostic x ray products',
 'Medical diagnostic gamma cameras and related products',
 'Brachytherapy products',
 'Gamma radiation therapy products',
 'Medical linear accelerator intensity modulated radiation therapy IMRT products',
 'Medical positron emission tomography PET equipment and related products',
 'Medical single photon emission computed tomography SPECT equipment and related products',
 'Radiotherapy teletherapy products',
 'Medical linear accelerators and related products',
 'Radiobiological instruments',
 'Radiotherapy simulators',
 'Vascular imaging and interventional cardiology and cardiac catheterization lab products',
 'Cardiac pacemakers and related products',
 'Medical radiological imaging information and archiving products',
 'Medical imaging processing equipment and supplies',
 'Medical radiological positioning aids',
 'Medical radiation detection or monitoring products',
 'Medical radiological shielding and protection products',
 'Ambulation and transfer and positioning aids for the physically challenged',
 'Bathroom and bathing aids for the physically challenged',
 'Communication aids for the physically challenged',
 'Dressing and grooming aids for the physically challenged',
 'Eating and drinking and food preparation aids for the physically challenged',
 'Leisure and recreational aids for the physically challenged',
 'Medication handling aids for the physically challenged',
 'Intravenous and arterial cannulas and catheters and accessories',
 'Intravenous and arterial tubing and administration sets and related products',
 'Intravenous and arterial infusion bags and containers and related products',
 'Intravenous and arterial catheter and needle positioning aids',
 'Intravenous or arterial flow measurement and regulation products',
 'Intravenous infusion pumps and its analyzers and sensors and its accessories',
 'Needleless intravenous injection and withdrawal systems',
 'Blood administration and transfusion products',
 'Enteral feeding equipment and supplies',
 'Gastrostomy and jejunostomy access devices or accessories',
 'Nasoenteric tubes',
 'Breast feeding equipment and supplies',
 'Tablet crushers and cutters and related products',
 'Casting and splinting supplies',
 'Casting equipment and parts and accessories',
 'Orthopedic softgoods for lower extremity',
 'Orthopedic softgoods for upper extremity and torso',
 'Prosthetic devices or accessories and supplies',
 'Orthopedic traction supplies and accessories',
 'Cognitive and dexterity and perceptual and sensory evaluation and therapy products',
 'Rehabilitation exercise devices and equipment',
 'Gait training products',
 'Work hardening equipment for rehabilitation or therapy',
 'Pathology dissection instruments and supplies',
 'Embalming equipment and supplies',
 'Mortuary equipment and supplies',
 'Respiratory monitoring products',
 'Pulmonary function testing and treatment products',
 'Oxygen therapy delivery systems and devices',
 'Respiratory humidity and aerosol therapy products',
 'Airway management products',
 'Intubation supplies',
 'Negative mechanical pressure ventilators',
 'Positive mechanical pressure ventilators and accessories',
 'Resuscitation supplies',
 'Anesthesia apparatus and accessories and supplies',
 'Surgical bone biopsy instruments and related products',
 'Surgical cutting instruments and snares and related products',
 'Surgical clamps and forceps and surgical ligators and related instruments',
 'Surgical instrument and tube holders and positioners',
 'Surgical inserters and extractors and related products',
 'Surgical approximators and compressors and depressors and related products',
 'Surgical bending irons and crimpers and pliers and tensioners and wrenches and related products',
 'Surgical taps and drivers and related products',
 'Surgical hammers and mallets and impactors and presses and related products',
 'Surgical dilators and probes and grooves and related products',
 'Surgical dissectors and elevators and picks and related products',
 'Suture and surgical tissue closure instruments and related products',
 'Surgical measuring devices and related products',
 'Surgical retractors and related products',
 'Surgical distractors and spreaders and separators and related products',
 'Surgical manipulators and implant positioners and related products',
 'Surgical suction and irrigation cannulas and tips and stylets and related products',
 'Surgical bougies and sounds and obturators and related products',
 'Surgical spatulas and spoons and scoops and related products',
 'Surgical instrument sets and systems and trays',
 'Vascular and cardiac systems',
 'Ophthalmic specialty instruments and related products',
 'Autotransfusion products',
 'Open heart perfusion equipment and monitors and accessories and related products',
 'Endoscopes and accessories and related products',
 'Endoscopic instruments and supplies and accessories and related products',
 'Endoscopic equipment and accessories and related products',
 'Surgical equipment and accessories and related products',
 'Surgical power equipment and accessories and related products',
 'Open heart surgical supplies and accessories and related products',
 'Surgical support supplies',
 'Surgical implants and expanders and extenders and surgical wires and related products',
 'Aids for medical training',
 'Bandages and dressings and related products',
 'Medical incision drains and drainage bags and reservoirs and related products',
 'Medical tissue closure and related products',
 'Ostomy supplies and non surgical wound drainage products',
 'Suture and related products',
 'Wound supports and supplies and accessories',
 'Personal communication devices',
 'Personal communications device accessories or parts',
 'System Cards',
 'System boards processors interfaces or modules',
 'Chassis components',
 'Media storage devices',
 'Media storage device accessories',
 'Removable storage media',
 'Computers',
 'Computer accessories',
 'Computer data input devices',
 'Computer displays',
 'Computer display accessories',
 'Computer printers',
 'Call management systems or accessories',
 'Fixed network equipment and components',
 'Network security equipment',
 'Network service equipment',
 'Telegraph equipment',
 'Teletype equipment',
 'Digital mobile network infrastructure equipment and components',
 'Mobile messaging platforms',
 'Datacom and network connectivity installation devices and equipment',
 'Business function specific software',
 'Finance accounting and enterprise resource planning ERP software',
 'Computer game or entertainment software',
 'Content authoring and editing software',
 'Content management software',
 'Data management and query software',
 'Development software',
 'Educational or reference software',
 'Industry specific software',
 'Network applications software',
 'Network management software',
 'Networking software',
 'Operating environment software',
 'Security and protection software',
 'Utility and device driver software',
 'Information exchange software',
 'System management software',
 'Duplicating machines',
 'Calculating machines and accessories',
 'Check endorsing and writing machines',
 'Mail machines',
 'Packing machines',
 'Labeling machines',
 'Sorting machines',
 'Typing machines and accessories',
 'Binding and lamination machines',
 'Lecterns and sound systems and accessories',
 'Projectors and supplies',
 'Audio presentation and composing equipment and hardware and controllers',
 'Video and combination video and audio presentation equipment and hardware and controllers',
 'Phone and video conference equipment and hardware and controllers',
 'Microfilm equipment and supplies',
 'Cameras',
 'Security and control equipment',
 'Traffic control',
 'Surveillance and detection equipment',
 'Washing and drying equipment',
 'Ironing equipment',
 'Dry cleaning equipment',
 'Floor machines and accessories',
 'Waste containers and accessories',
 'Piece and part vending machines',
 'Service and ticket vending machines',
 'Currency vending machines',
 'Aerobic training equipment',
 'Weight and resistance training equipment',
 'Domestic kitchen appliances',
 'Domestic laundry appliances and supplies',
 'Domestic bath appliances',
 'Other domestic household appliances',
 'Audio and visual equipment',
 'Audio visual equipment accessories',
 'Electronic publications and music',
 'Art and craft cutting products',
 'Transport buildings and structures',
 'Prefabricated commercial and industrial buildings and structures']
