creative_tech = ['Art and craft cutting products',
'Picture framing',
'Drawing tools and supplies and accessories',
'Studio aids',
'Printmaking supplies and accessories',
'Sewing and stitchery and weaving equipment and accessories',
'Candlemaking',
'Wood crafts',
'Stained glass making supplies',
'Paper crafts and hand made papermaking',
'Enameling paints and accessories',
'Beads or beading accessories',
'Leather craft materials',
'Glitter',
'Macrame craft materials and accessories',
'Clay and modeling compounds and ceramics equipment and accessories',
'Sculpture supplies and accessories',
'Keyboard instruments',
'Brass instruments',
'Woodwind instruments',
'String instruments',
'Percussion instruments',
'Musical instrument parts and accessories',
'Musical instrument sets',
'Toys',
'Games',
'Active play equipment and accessories',
'Dramatic play equipment and accessories']
