machines = ['Mining and Well Drilling Machinery and Accessories',
 'Farming and Fishing and Forestry and Wildlife Machinery and Accessories',
 'Building and Construction Machinery and Accessories',
 'Industrial Manufacturing and Processing Machinery and Accessories',
 'Material Handling and Conditioning and Storage Machinery and their Accessories and Supplies',
 'Power Generation and Distribution Machinery and Accessories',
 'Tools and General Machinery',
 'Laboratory and Measuring and Observing and Testing Equipment',
 'Medical Equipment and Accessories and Supplies',
 'Information Technology Broadcasting and Telecommunications',
 'Printing and Photographic and Audio and Visual Equipment and Supplies',
 'Service Industry Machinery and Equipment and Supplies',
 'Domestic Appliances and Supplies and Consumer Electronic Products',
 'Land and Buildings and Structures and Thoroughfares']
